[features]
seeds = false
skip-lint = false
[programs.localnet]
kivo = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/frankfinnegan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
push = "anchor deploy -p kivo --provider.cluster devnet && anchor idl upgrade --filepath ./target/idl/kivo.json 5p53sbjVpoDizJ8CaaVrJ7ZirXAH6AZNUysd75rnn98p --provider.cluster devnet"